# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js Test CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      matrix:
        node-version: [12.19, 14.16, 14.18, 16.15]

    steps:
    - uses: actions/checkout@v2
    - name: Setup unit test environment
      run: |-
        sudo apt-get update -y
        sudo apt-get install -y libwebp-dev libcairo2-dev libopenjp2-tools exiftool
        git clone https://github.com/ImageMagick/ImageMagick.git
        cd ImageMagick && git checkout 7.0.10-34
        ./configure -with-gcc-arch=core2 --enable-hdri=yes --enable-hugepages --enable-largefile --with-x=no --with-heic=no --with-magick-plus-plus=no --enable-static=no --disable-openmp --disable-opencl --disable-docs --without-perl --with-rsvg=yes --with-fontconfig=yes --with-xml=yes --with-webp=yes
        make && sudo make install && sudo ldconfig /usr/local/lib
        cd .. && rm -rf ImageMagick
        cd /usr/local/lib/ && rm -f *.a
        identify -version
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test

  sizewatcher:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - uses: actions/checkout@v2
    - run: npx @adobe/sizewatcher
  semantic-release:
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{  !contains(github.event.head_commit.message, '[ci skip]') && github.ref == 'refs/heads/master' }}
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Use Node.js 14.18
        uses: actions/setup-node@v1
        with:
          node-version: '14.18'
      - run: npm install
      - run: npm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.ADOBE_BOT_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.ADOBE_BOT_NPM_TOKEN }}
